--- # PRODUCTION PROFILE
spring:
  config:
    activate:
      on-profile: prod

springdoc:
  api-docs:
    enabled: false
  swagger-ui:
    enabled: false

amazon:
  dynamodb:
    endpoint: ${AMAZON_DYNAMODB_ENDPOINT}
    region: ${AMAZON_DYNAMODB_REGION}
    accessKey: ${AMAZON_DYNAMODB_ACCESS_KEY}
    secretKey: ${AMAZON_DYNAMODB_SECRET_KEY}
  s3:
    region: ${AMAZON_S3_REGION}
    accessKey: ${AMAZON_S3_ACCESS_KEY}
    secretKey: ${AMAZON_S3_SECRET_KEY}
    bucket: ${AMAZON_S3_BUCKET}
  sns:
    region: ${AMAZON_SNS_REGION}
    accessKey: ${AMAZON_SNS_ACCESS_KEY}
    secretKey: ${AMAZON_SNS_SECRET_KEY}